(function(){
  // Catálogo base. Idealmente mantener sincronizado con Productos.html
  // id/slug generado desde el nombre en minúsculas con guiones
  window.PRODUCTS = [
    { id: 'jabon-liquido', name: 'Jabón líquido', price: 1600, image: './Imagenes/Productos/jabon-liquido.jpg' },
    { id: 'suavizante', name: 'Suavizante', price: 1600, image: './Imagenes/Productos/suavizante.jpg' },
    { id: 'cloro', name: 'Cloro', price: 1800, image: './Imagenes/Productos/cloro.jpg' },
    { id: 'lavandina', name: 'Lavandina', price: 1500, image: './Imagenes/Productos/lavandina.jpg' },
    { id: 'perfumine-ropa', name: 'Perfumine para ropa', price: 3000, image: './Imagenes/Productos/perfumine-ropa.jpg' },
    { id: 'desodorante-piso', name: 'Desodorante de piso', price: 1500, image: './Imagenes/Productos/desodorante-piso.jpg' },
    { id: 'esponjitas-plato', name: 'Esponjitas para plato', price: 500, image: './Imagenes/Productos/esponjitas-plato.jpg' },
    { id: 'trapo-piso-gris', name: 'Trapo de piso gris (consorcio)', price: 1500, image: './Imagenes/Productos/trapo-piso-gris.jpg' },
    { id: 'trapo-piso-blanco', name: 'Trapo de piso blanco', price: 1500, image: './Imagenes/Productos/trapo-piso-blanco.jpg' },
    { id: 'escobillon', name: 'Escobillón', price: 3500, image: './Imagenes/Productos/escobillon.jpg' },
    { id: 'palo-escobillon', name: 'Palo para escobillón', price: 2500, image: './Imagenes/Productos/palo-escobillon.jpg' },
    { id: 'secador-piso-grande', name: 'Secador de piso grande', price: 2800, image: './Imagenes/Productos/secador-piso-grande.jpg' },
    { id: 'palita-basura-mano', name: 'Palita de basura de mano', price: 1200, image: './Imagenes/Productos/palita-basura-mano.jpg' },
    { id: 'palita-mango', name: 'Palita con mango', price: 2500, image: './Imagenes/Productos/palita-mango.jpg' },
    { id: 'cepillo-ropa', name: 'Cepillo para la ropa', price: 2000, image: './Imagenes/Productos/cepillo-ropa.jpg' },
    { id: 'cepillo-zapatilla', name: 'Sopillo para zapatilla', price: 1500, image: './Imagenes/Productos/cepillo-zapatilla.jpg' },
    { id: 'cepillo-lava-auto', name: 'Cepillo lava auto', price: 3000, image: './Imagenes/Productos/cepillo-lava-auto.jpg' },
    { id: 'saca-telas', name: 'Saca telas', price: 1200, image: './Imagenes/Productos/saca-telas.jpg' },
    { id: 'esponja-alambre', name: 'Esponja de alambre (30 g)', price: 3500, image: './Imagenes/Productos/esponja-alambre.jpg' },
    { id: 'rejilla-blanca', name: 'Rejilla blanca', price: 1000, image: './Imagenes/Productos/rejilla-blanca.jpg' },
    { id: 'cejilla-amarilla', name: 'Cejilla amarilla', price: 800, image: './Imagenes/Productos/cejilla-amarilla.jpg' },
    { id: 'repasadores', name: 'Repasadores', price: 1500, image: './Imagenes/Productos/Repasadores.jpg' },
    { id: 'esponja-bano', name: 'Esponja de baño', price: 1000, image: './Imagenes/Productos/esponja-bano.jpg' },
    { id: 'lampazo-amarillo', name: 'Lampazo amarillo', price: 2500, image: './Imagenes/Productos/lampazo-amarillo.jpg' },
    { id: 'lampazo-blanco', name: 'Lampazo blanco', price: 3000, image: './Imagenes/Productos/lampazo-blanco.jpg' },
    { id: 'detergente-amarillo', name: 'Detergente amarillo', price: 2500, image: './Imagenes/Productos/detergente-amarillo.jpg' },
    { id: 'desengrasante', name: 'Desengrasante', price: 3000, image: './Imagenes/Productos/desengrasante.jpg' },
    { id: 'quita-mancha', name: 'Quita mancha', price: 2500, image: './Imagenes/Productos/quita-mancha.jpg' },
    { id: 'pastilla-cloro-grande', name: 'Pastilla de cloro grande', price: 3500, image: './Imagenes/Productos/pastilla-cloro-grande.jpg' },
    { id: 'pastilla-cloro-chica', name: 'Pastilla de cloro chica', price: 2000, image: './Imagenes/Productos/pastilla-cloro-chica.jpg' },
    { id: 'saca-bicho', name: 'Saca bicho', price: 3500, image: './Imagenes/Productos/saca-bicho.jpg' },
    { id: 'limpia-vidrio', name: 'Limpia vidrio', price: 2500, image: './Imagenes/Productos/limpia-vidrio.jpg' },
    { id: 'alcohol-liquido', name: 'Alcohol líquido', price: 3000, image: './Imagenes/Productos/alcohol-liquido.jpg' },
    { id: 'alcohol-gel', name: 'Alcohol en gel', price: 3500, image: './Imagenes/Productos/alcohol-gel.jpg' },
    { id: 'lavandina-gel', name: 'Lavandina en gel', price: 3500, image: './Imagenes/Productos/lavandina-gel.jpg' },
    { id: 'alimento-gato', name: 'Alimento para gato', price: 2600, image: './Imagenes/Productos/alimento-gato.jpg' },
    { id: 'alimento-perro-chico', name: 'Alimento para perro raza pequeña', price: 2500, image: './Imagenes/Productos/alimento-perro-chico.jpg' },
    { id: 'alimento-perro-adulto', name: 'Alimento para perro adulto', price: 2400, image: './Imagenes/Productos/alimento-perro-adulto.jpg' },
    { id: 'piedra-gato', name: 'Piedra para gato', price: 2000, image: './Imagenes/Productos/piedra-gato.jpg' },
    { id: 'virulanas', name: 'Virulanas', price: 800, image: './Imagenes/Productos/virulanas.jpg' },
    { id: 'regador-manguera', name: 'Regador para manguera', price: 2500, image: './Imagenes/Productos/regador-manguera.jpg' },
    { id: 'hipoclorito-pileta', name: 'Hipoclorito para pileta', price: 3000, image: './Imagenes/Productos/hipoclorito-pileta.jpg' }
  ];
})();
