(function(){
  // Catálogo base. Idealmente mantener sincronizado con Productos.html
  // id/slug generado desde el nombre en minúsculas con guiones
  window.PRODUCTS = [
    { id: 'jabon-liquido', name: 'Jabón líquido', price: 1600, image: './Imagenes/Productos/JabonLiquido.jpg' },
    { id: 'suavizante', name: 'Suavizante', price: 1600, image: './Imagenes/Productos/Suavizante.jpg' },
    { id: 'cloro', name: 'Cloro', price: 1800, image: './Imagenes/Productos/Cloro.jpg' },
    { id: 'lavandina', name: 'Lavandina', price: 1500, image: './Imagenes/Productos/Lavandina.jpg' },
    { id: 'perfumine-ropa', name: 'Perfumine para ropa', price: 3000, image: './Imagenes/Productos/perfumina-para-ropa.jpg' },
    { id: 'desodorante-piso', name: 'Desodorante de piso', price: 1500, image: './Imagenes/Productos/Desodorante-de-piso.jpg' },
    { id: 'esponjitas-plato', name: 'Esponjitas para plato', price: 500, image: './Imagenes/Productos/Esponjitas-para-plato.jpg' },
    { id: 'trapo-piso-gris', name: 'Trapo de piso gris (consorcio)', price: 1500, image: './Imagenes/Productos/trapo-piso-gris-consorcio.jpg' },
    { id: 'trapo-piso-blanco', name: 'Trapo de piso blanco', price: 1500, image: './Imagenes/Productos/Trapo-de-piso-blanco.jpg' },
    { id: 'escobillon', name: 'Escobillón', price: 3500, image: './Imagenes/Productos/Escobillón.jpg' },
    { id: 'palo-escobillon', name: 'Palo para escobillón', price: 2500, image: './Imagenes/Productos/Palo.png' },
    { id: 'secador-piso-grande', name: 'Secador de piso grande', price: 2800, image: './Imagenes/Productos/Secador-de-piso-grande.jpg' },
    { id: 'palita-basura-mano', name: 'Palita de basura de mano', price: 1200, image: './Imagenes/Productos/Palita-de-mano.jpg' },
    { id: 'palita-mango', name: 'Palita con mango', price: 2500, image: './Imagenes/Productos/Palita con mango.png' },
    { id: 'cepillo-ropa', name: 'Cepillo para la ropa', price: 2000, image: './Imagenes/Productos/Cepillo-para-la-ropa.png' },
    { id: 'cepillo-zapatilla', name: 'Sopillo para zapatilla', price: 1500, image: './Imagenes/Productos/Cepillo para zapatilla.jpg' },
    { id: 'cepillo-lava-auto', name: 'Cepillo lava auto', price: 3000, image: './Imagenes/Productos/Cepillo-lava-auto.png' },
    { id: 'saca-telas', name: 'Saca telas', price: 1200, image: './Imagenes/Productos/Saca-telas.jpg' },
    { id: 'esponja-alambre', name: 'Esponja de alambre (30 g)', price: 3500, image: './Imagenes/Productos/Esponja-de-alambre-(30 g).jpg' },
    { id: 'rejilla-blanca', name: 'Rejilla blanca', price: 1000, image: './Imagenes/Productos/Rejilla-blanca.jpg' },
    { id: 'cejilla-amarilla', name: 'Cejilla amarilla', price: 800, image: './Imagenes/Productos/Cejilla-amarilla.jpg' },
    { id: 'repasadores', name: 'Repasadores', price: 1500, image: './Imagenes/Productos/Repasadores.jpg' },
    { id: 'esponja-bano', name: 'Esponja de baño', price: 1000, image: './Imagenes/Productos/Esponja-de-baño.jpg' },
    { id: 'lampazo-amarillo', name: 'Lampazo amarillo', price: 2500, image: './Imagenes/Productos/Lampazo-blanco.jpg' },
    { id: 'lampazo-blanco', name: 'Lampazo blanco', price: 3000, image: './Imagenes/Productos/Lampazo-blanco.jpg' },
    { id: 'detergente-amarillo', name: 'Detergente amarillo', price: 2500, image: './Imagenes/Productos/Detergente-amarillo.jpg' },
    { id: 'desengrasante', name: 'Desengrasante', price: 3000, image: './Imagenes/Productos/Desengrasante.jpg' },
    { id: 'quita-mancha', name: 'Quita mancha', price: 2500, image: './Imagenes/Productos/Quita-mancha.jpg' },
    { id: 'pastilla-cloro-grande', name: 'Pastilla de cloro grande', price: 3500, image: './Imagenes/Productos/Pastilla-de-cloro-grande.jpg' },
    { id: 'pastilla-cloro-chica', name: 'Pastilla de cloro chica', price: 2000, image: './Imagenes/Productos/Pastilla-de-cloro-chica.jpg' },
    { id: 'saca-bicho', name: 'Saca bicho', price: 3500, image: './Imagenes/Productos/Saca-bicho.jpg' },
    { id: 'limpia-vidrio', name: 'Limpia vidrio', price: 2500, image: './Imagenes/Productos/Limpia-vidrio.jpg' },
    { id: 'alcohol-liquido', name: 'Alcohol líquido', price: 3000, image: './Imagenes/Productos/Alcohol-líquido.jpg' },
    { id: 'alcohol-gel', name: 'Alcohol en gel', price: 3500, image: './Imagenes/Productos/Alcohol-en-gel.jpg' },
    { id: 'lavandina-gel', name: 'Lavandina en gel', price: 3500, image: './Imagenes/Productos/Lavandina-en-gel.jpg' },
    { id: 'alimento-gato', name: 'Alimento para gato', price: 2600, image: './Imagenes/Productos/Alimento-para-gato.jpg' },
    { id: 'alimento-perro-chico', name: 'Alimento para perro raza pequeña', price: 2500, image: './Imagenes/Productos/Alimento-para-perro-raza-pequeña.jpg' },
    { id: 'alimento-perro-adulto', name: 'Alimento para perro adulto', price: 2400, image: './Imagenes/Productos/Alimento-para-perro-adulto.jpg' },
    { id: 'piedra-gato', name: 'Piedra para gato', price: 2000, image: './Imagenes/Productos/Piedra-para-gato.jpg' },
    { id: 'virulanas', name: 'Virulanas', price: 800, image: './Imagenes/Productos/Virulanas.jpg' },
    { id: 'regador-manguera', name: 'Regador para manguera', price: 2500, image: './Imagenes/Productos/Regador-para-manguera.jpg' },
    { id: 'hipoclorito-pileta', name: 'Hipoclorito para pileta', price: 3000, image: './Imagenes/Productos/Hipoclorito-para-pileta.jpg' }
  ];
})();
